version: "3.8"

services:
  database:
    container_name: db-postgre-project_name
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # default: /var/lib/postgresql/data better in a subfolder for volume mounts
      # see https://hub.docker.com/_/postgres
      - PGDATA=/var/lib/postgresql/data/project_name_data
      # REF: https://stackoverflow.com/a/63824663/13677125
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

  # minio:
  #   container_name: minio-s3-project_name
  #   image: minio/minio
  #   command: server /data --console-address ":9001"
  #   hostname: minio
  #   ports:
  #     # outside:inside
  #     - 9099:9000
  #     - 9001:9001
  #     # - 9002:9002
  #     # environment:
  #     # MINIO_ROOT_USER: minioadmin
  #     # MINIO_ROOT_PASSWORD: minioadmin
  #   volumes:
  #     - .minio:/data